"""Overdue Receivables Report - Generate and email an HTML report.

Fetches overdue receivables older than 30 days, generates an HTML
email report, and sends it via SMTP.

Environment variables:
    TALLYBRIDGE_TALLY_HOST: Tally host (default: localhost)
    TALLYBRIDGE_TALLY_PORT: Tally port (default: 9000)
    TALLYBRIDGE_TALLY_COMPANY: Company name (optional)
    SMTP_HOST: SMTP server hostname
    SMTP_PORT: SMTP server port (default: 587)
    SMTP_USER: SMTP login username
    SMTP_PASSWORD: SMTP login password
    REPORT_TO: Recipient email address
    REPORT_FROM: Sender email address (default: SMTP_USER)
"""

import os
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from loguru import logger
from pydantic_settings import BaseSettings, SettingsConfigDict
from rich.console import Console
from rich.table import Table

import tallybridge
from tallybridge.exceptions import TallyConnectionError


class SMTPConfig(BaseSettings):
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""
    report_to: str = ""
    report_from: str = ""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )

    @property
    def is_configured(self) -> bool:
        return all([self.smtp_host, self.smtp_user, self.smtp_password, self.report_to])

    @property
    def sender(self) -> str:
        return self.report_from or self.smtp_user


def _build_html_report(bills: list[tallybridge.OutstandingBill]) -> str:
    rows_html = ""
    for bill in bills:
        rows_html += (
            f"<tr>"
            f"<td>{bill.party_name}</td>"
            f"<td>{bill.bill_date.isoformat()}</td>"
            f"<td>{bill.bill_number}</td>"
            f"<td style='text-align:right'>&#8377;{bill.bill_amount:,.2f}</td>"
            f"<td style='text-align:right'>&#8377;{bill.outstanding_amount:,.2f}</td>"
            f"<td style='text-align:right'>{bill.overdue_days}</td>"
            f"</tr>"
        )

    total_outstanding = sum(b.outstanding_amount for b in bills)

    return f"""\
<html>
<body style="font-family: Arial, sans-serif; margin: 20px;">
<h2>Overdue Receivables Report</h2>
<p>Showing bills overdue by 30+ days. Total outstanding: &#8377;{total_outstanding:,.2f}</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse;">
<thead>
<tr style="background-color: #f2f2f2;">
<th>Party</th><th>Bill Date</th><th>Bill No.</th>
<th>Bill Amount</th><th>Outstanding</th><th>Days Overdue</th>
</tr>
</thead>
<tbody>
{rows_html}
</tbody>
</table>
<p style="color: #888; font-size: 12px;">Generated by TallyBridge</p>
</body>
</html>"""


def _build_console_table(bills: list[tallybridge.OutstandingBill]) -> Table:
    table = Table(title="Overdue Receivables (30+ days)", show_lines=True)
    table.add_column("Party", style="bold")
    table.add_column("Bill Date")
    table.add_column("Bill No.")
    table.add_column("Bill Amount", justify="right", style="green")
    table.add_column("Outstanding", justify="right", style="red")
    table.add_column("Days Overdue", justify="right", style="yellow")

    for bill in bills:
        table.add_row(
            bill.party_name,
            bill.bill_date.isoformat(),
            bill.bill_number,
            f"\u20b9{bill.bill_amount:,.2f}",
            f"\u20b9{bill.outstanding_amount:,.2f}",
            str(bill.overdue_days),
        )

    return table


def _send_email(html: str, config: SMTPConfig) -> None:
    if not config.is_configured:
        logger.warning("SMTP config incomplete — skipping email")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Overdue Receivables Report"
    msg["From"] = config.sender
    msg["To"] = config.report_to
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(config.smtp_host, config.smtp_port, timeout=30) as server:
            server.starttls()
            server.login(config.smtp_user, config.smtp_password)
            server.sendmail(config.sender, [config.report_to], msg.as_string())
        logger.info("Email sent to {}", config.report_to)
    except smtplib.SMTPException as exc:
        logger.error("Failed to send email: {}", exc)


def main() -> None:
    console = Console()
    smtp_config = SMTPConfig()

    try:
        q = tallybridge.connect(
            tally_host=os.getenv("TALLYBRIDGE_TALLY_HOST", "localhost"),
            tally_port=int(os.getenv("TALLYBRIDGE_TALLY_PORT", "9000")),
            company=os.getenv("TALLYBRIDGE_TALLY_COMPANY"),
        )
    except TallyConnectionError as exc:
        console.print(f"[bold red]Tally is not connected:[/bold red] {exc}")
        console.print("Please ensure TallyPrime is running with HTTP server enabled on port 9000.")
        sys.exit(0)

    bills = q.get_receivables(overdue_only=True, min_days_overdue=30)

    if not bills:
        console.print("[green]No overdue receivables found.[/green]")
        return

    table = _build_console_table(bills)
    console.print(table)

    html = _build_html_report(bills)
    _send_email(html, smtp_config)


if __name__ == "__main__":
    main()
